basePath: /api/v1
definitions:
  model.UserLoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  model.ValidationError:
    properties:
      code:
        type: string
      message:
        type: string
      param:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Virdan Project API Documentation
  title: Virdan API
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: file(docs/flows/login.md)
      parameters:
      - description: Payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserLoginRequest'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ValidationError'
      summary: Login user
      tags:
      - auth
swagger: "2.0"
